import { Brief, Proposal, SalesComment, BrandExplorer, LibraryProposal, User, Client, Event } from "./types"

export const currentUser: User = {
  id: "user-1",
  name: "Fajar Pahlawan H.",
  email: "fajar.p@rectoverso.com",
  role: "Supervisor",
}

export const users: User[] = [
  currentUser,
  { id: "user-2", name: "Budi Setiawan", email: "budi.s@rectoverso.com", role: "Sales" },
  { id: "user-3", name: "Andi Pratama", email: "andi.p@rectoverso.com", role: "Sales" },
  { id: "user-4", name: "Dita Amelia", email: "dita.a@rectoverso.com", role: "ACS" },
  { id: "user-5", name: "Rizky Firmansyah", email: "rizky.f@rectoverso.com", role: "Supervisor" },
]

export const briefs: Brief[] = [
  {
    id: "brief-1",
    brand_name: "Wardah",
    industry_category: "Beauty & Personal Care",
    pic_sales: "Budi Setiawan",
    pic_contact: "budi@wardah.com",
    program: "Sinetron Ramadan",
    sponsorship_type: "Segment Sponsor",
    objective: "Meningkatkan brand awareness dan consideration selama Ramadan",
    target_audience: "Perempuan 20-45 tahun",
    period: "Ramadan 2025",
    deadline: "2025-05-27",
    budget_range: "Rp 1.000.000.000 - 1.500.000.000",
    budget_note: "Flexible untuk paket yang tepat",
    notes: "Fokus pada momen Ramadan dan nilai keluarga",
    attachments: [],
    status: "new",
    created_at: "2025-05-19",
    created_by: "user-2",
  },
  {
    id: "brief-2",
    brand_name: "OPPO",
    industry_category: "Technology",
    pic_sales: "Dita Amelia",
    pic_contact: "dita@oppo.com",
    program: "Sinetron",
    sponsorship_type: "Segment Sponsor",
    objective: "Memperkuat brand image OPPO Reno Series di kalangan anak muda",
    target_audience: "Remaja 18-30 tahun",
    period: "Q3 2025",
    deadline: "2025-06-15",
    budget_range: "Rp 800.000.000 - 1.200.000.000",
    budget_note: "Open untuk negosiasi",
    notes: "Butuh ide integrasi kreatif untuk karakter sinetron",
    attachments: [],
    status: "in_progress",
    created_at: "2025-05-18",
    created_by: "user-4",
  },
  {
    id: "brief-3",
    brand_name: "Indomie",
    industry_category: "Food & Beverage",
    pic_sales: "Andi Pratama",
    pic_contact: "andi@indomie.com",
    program: "Reality Show",
    sponsorship_type: "Program Sponsor",
    objective: "Menunjukkan aspek family-friendly brand Indomie",
    target_audience: "Keluarga Indonesia",
    period: "Q2 2025",
    deadline: "2025-06-10",
    budget_range: "Rp 1.500.000.000 - 2.000.000.000",
    budget_note: "Budget locked",
    notes: "Minta showcase produk di segment",
    attachments: [],
    status: "in_review",
    created_at: "2025-05-17",
    created_by: "user-3",
  },
  {
    id: "brief-4",
    brand_name: "Shopee",
    industry_category: "E-commerce",
    pic_sales: "Rizky Firmansyah",
    pic_contact: "rizky@shopee.com",
    program: "Variety Show",
    sponsorship_type: "Title Sponsor",
    objective: "Meningkatkan traffic dan sales selama 6.6 Big Sale",
    target_audience: "Pengguna online shopping 20-40 tahun",
    period: "Juni 2025",
    deadline: "2025-06-01",
    budget_range: "Rp 2.000.000.000 - 3.000.000.000",
    budget_note: "Flexible",
    notes: "Integrasi dengan flash sale segment",
    attachments: [],
    status: "in_progress",
    created_at: "2025-05-15",
    created_by: "user-5",
  },
  {
    id: "brief-5",
    brand_name: "Aqua",
    industry_category: "Beverages",
    pic_sales: "Budi Setiawan",
    pic_contact: "budi@aqua.com",
    program: "Reality Show",
    sponsorship_type: "Segment Sponsor",
    objective: "Brand positioning sebagai air mineral 100% murni",
    target_audience: "Keluarga Indonesia 25-45 tahun",
    period: "Q2-Q3 2025",
    deadline: "2025-06-20",
    budget_range: "Rp 500.000.000 - 800.000.000",
    budget_note: "Open negosiasi",
    notes: "Fokus pada clean label messaging",
    attachments: [],
    status: "in_review",
    created_at: "2025-05-14",
    created_by: "user-2",
  },
  {
    id: "brief-6",
    brand_name: "Pepsodent",
    industry_category: "Healthcare",
    pic_sales: "Dita Amelia",
    pic_contact: "dita@pepsodent.com",
    program: "Sinetron",
    sponsorship_type: "Segment Sponsor",
    objective: "Edukasi kesehatan gigi dan mulut",
    target_audience: "Ibu dan anak 7-12 tahun",
    period: "2025",
    deadline: "2025-07-01",
    budget_range: "Rp 400.000.000 - 600.000.000",
    budget_note: "Fixed budget",
    notes: "Kolaborasi dengan cerita sinetron",
    attachments: [],
    status: "new",
    created_at: "2025-05-20",
    created_by: "user-4",
  },
  {
    id: "brief-7",
    brand_name: "Telkomsel",
    industry_category: "Telecommunication",
    pic_sales: "Andi Pratama",
    pic_contact: "andi@telkomsel.com",
    program: "Infotainment",
    sponsorship_type: "Official Sponsor",
    objective: "Promosi produk Halo+",
    target_audience: "Pengguna telepon 18-35 tahun",
    period: "2025",
    deadline: "2025-06-25",
    budget_range: "Rp 1.200.000.000 - 1.800.000.000",
    budget_note: "Flexible",
    notes: "Integration dengan program pengecekan pulsa",
    attachments: [],
    status: "in_progress",
    created_at: "2025-05-13",
    created_by: "user-3",
  },
  {
    id: "brief-8",
    brand_name: "Mie Sedaap",
    industry_category: "Food & Beverage",
    pic_sales: "Rizky Firmansyah",
    pic_contact: "rizky@sedaap.com",
    program: "Reality Show",
    sponsorship_type: "Segment Sponsor",
    objective: "Promosi varian Pedas Korea",
    target_audience: "Pecinta makanan pedas 18-35 tahun",
    period: "Q3 2025",
    deadline: "2025-07-15",
    budget_range: "Rp 600.000.000 - 900.000.000",
    budget_note: "Open",
    notes: "Challenge makan pedas segment",
    attachments: [],
    status: "new",
    created_at: "2025-05-21",
    created_by: "user-5",
  },
]

export const proposals: Proposal[] = [
  {
    id: "prop-1",
    title: "Wardah - Ramadan Campaign 2024",
    brand_name: "Wardah",
    program: "Sinetron Ramadan",
    industry: "Beauty & Personal Care",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "ready",
    result: "won",
    pic_sales: "Budi Setiawan",
    deadline: "2025-05-27",
    last_activity: "Hari ini, 14:32",
    slides_count: 28,
    created_at: "2024-03-01",
    updated_at: "2024-03-15",
  },
  {
    id: "prop-2",
    title: "OPPO - Reno Series",
    brand_name: "OPPO",
    program: "Sinetron",
    industry: "Technology",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "drafting",
    result: undefined,
    pic_sales: "Dita Amelia",
    deadline: "2025-06-15",
    last_activity: "Kemarin, 16:45",
    slides_count: 24,
    created_at: "2024-04-10",
    updated_at: "2024-04-20",
  },
  {
    id: "prop-3",
    title: "Indomie - Family Moment",
    brand_name: "Indomie",
    program: "Reality Show",
    industry: "Food & Beverage",
    sponsorship_type: "Program Sponsor",
    year: 2024,
    status: "drafting",
    result: undefined,
    pic_sales: "Andi Pratama",
    deadline: "2025-06-10",
    last_activity: "2 hari lalu, 10:30",
    slides_count: 22,
    created_at: "2024-04-15",
    updated_at: "2024-04-25",
  },
  {
    id: "prop-4",
    title: "Shopee - 6.6 Big Sale",
    brand_name: "Shopee",
    program: "Variety Show",
    industry: "E-commerce",
    sponsorship_type: "Title Sponsor",
    year: 2024,
    status: "drafting",
    result: undefined,
    pic_sales: "Rizky Firmansyah",
    deadline: "2025-06-01",
    last_activity: "3 hari lalu, 09:15",
    slides_count: 32,
    created_at: "2024-04-20",
    updated_at: "2024-05-01",
  },
  {
    id: "prop-5",
    title: "Aqua - 100% Murni",
    brand_name: "Aqua",
    program: "Reality Show",
    industry: "Beverages",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "need_input",
    result: undefined,
    pic_sales: "Budi Setiawan",
    deadline: "2025-06-20",
    last_activity: "4 hari lalu, 11:00",
    slides_count: 20,
    created_at: "2024-04-25",
    updated_at: "2024-05-02",
  },
  {
    id: "prop-6",
    title: "Pepsodent - Total Care",
    brand_name: "Pepsodent",
    program: "Sinetron",
    industry: "Healthcare",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "need_input",
    result: undefined,
    pic_sales: "Dita Amelia",
    deadline: "2025-07-01",
    last_activity: "1 minggu lalu, 15:30",
    slides_count: 18,
    created_at: "2024-05-01",
    updated_at: "2024-05-05",
  },
  {
    id: "prop-7",
    title: "Telkomsel - Halo+",
    brand_name: "Telkomsel",
    program: "Infotainment",
    industry: "Telecommunication",
    sponsorship_type: "Official Sponsor",
    year: 2024,
    status: "need_input",
    result: undefined,
    pic_sales: "Andi Pratama",
    deadline: "2025-06-25",
    last_activity: "5 hari lalu, 08:45",
    slides_count: 26,
    created_at: "2024-05-05",
    updated_at: "2024-05-10",
  },
  {
    id: "prop-8",
    title: "Mie Sedaap - Pedas Korea",
    brand_name: "Mie Sedaap",
    program: "Reality Show",
    industry: "Food & Beverage",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "revised",
    result: undefined,
    pic_sales: "Rizky Firmansyah",
    deadline: "2025-07-15",
    last_activity: "1 minggu lalu, 13:20",
    slides_count: 24,
    created_at: "2024-05-08",
    updated_at: "2024-05-15",
  },
  {
    id: "prop-9",
    title: "Vaseline - Healthy Bright",
    brand_name: "Vaseline",
    program: "Sinetron",
    industry: "Beauty & Personal Care",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "revised",
    result: undefined,
    pic_sales: "Budi Setiawan",
    deadline: "2025-06-30",
    last_activity: "2 minggu lalu, 16:00",
    slides_count: 22,
    created_at: "2024-05-10",
    updated_at: "2024-05-18",
  },
  {
    id: "prop-10",
    title: "Honda - One HEART",
    brand_name: "Honda",
    program: "Sports Program",
    industry: "Automotive",
    sponsorship_type: "Program Sponsor",
    year: 2023,
    status: "ready",
    result: "won",
    pic_sales: "Andi Pratama",
    deadline: "2024-12-31",
    last_activity: "3 bulan lalu",
    slides_count: 32,
    created_at: "2023-06-01",
    updated_at: "2023-06-20",
  },
  {
    id: "prop-11",
    title: "Hydro Coco - Sports Time",
    brand_name: "Hydro Coco",
    program: "Sports Program",
    industry: "Beverages",
    sponsorship_type: "Official Sponsor",
    year: 2024,
    status: "ready",
    result: "won",
    pic_sales: "Dita Amelia",
    deadline: "2025-05-15",
    last_activity: "1 bulan lalu",
    slides_count: 28,
    created_at: "2024-04-01",
    updated_at: "2024-04-15",
  },
  {
    id: "prop-12",
    title: "SariWangi - Pilihan Keluarga",
    brand_name: "SariWangi",
    program: "Sinetron",
    industry: "Food & Beverage",
    sponsorship_type: "Segment Sponsor",
    year: 2024,
    status: "ready",
    result: "won",
    pic_sales: "Rizky Firmansyah",
    deadline: "2025-04-30",
    last_activity: "2 bulan lalu",
    slides_count: 24,
    created_at: "2024-03-15",
    updated_at: "2024-03-30",
  },
]

export const libraryProposals: LibraryProposal[] = [
  {
    id: "lib-1",
    title: "Wardah Ramadan Campaign 2024",
    brand_name: "Wardah",
    program: "Sinetron Ramadan",
    industry: "Beauty & Personal Care",
    sponsorship_type: "Segment",
    year: 2024,
    status: "won",
    last_viewed: "Hari ini",
    slides_count: 28,
    tags: ["Segment", "2024", "28 slides"],
  },
  {
    id: "lib-2",
    title: "OPPO - Reno Series",
    brand_name: "OPPO",
    program: "Sinetron",
    industry: "Technology",
    sponsorship_type: "Segment",
    year: 2024,
    status: "won",
    last_viewed: "Kemarin",
    slides_count: 24,
    tags: ["Segment", "2024", "24 slides"],
  },
  {
    id: "lib-3",
    title: "Indomie - Family Moment",
    brand_name: "Indomie",
    program: "Reality Show",
    industry: "Food & Beverage",
    sponsorship_type: "Program",
    year: 2024,
    status: "pitched",
    last_viewed: "2 hari lalu",
    slides_count: 22,
    tags: ["Program", "2024", "22 slides"],
  },
  {
    id: "lib-4",
    title: "Honda - One HEART",
    brand_name: "Honda",
    program: "Sports Program",
    industry: "Automotive",
    sponsorship_type: "Program",
    year: 2023,
    status: "won",
    last_viewed: "3 hari lalu",
    slides_count: 32,
    tags: ["Program", "2023", "32 slides"],
  },
]

export const salesComments: SalesComment[] = [
  {
    id: "comment-1",
    proposal_id: "prop-5",
    user_id: "user-2",
    user_name: "Budi Setiawan",
    user_role: "Sales",
    content: "Client minta dipertimbangkan untuk penambahan integration di scene makan. Mohon ditambahkan di proposal.",
    timestamp: "10:30",
  },
  {
    id: "comment-2",
    proposal_id: "prop-6",
    user_id: "user-3",
    user_name: "Andi Pratama",
    user_role: "Sales",
    content: "Budget client naik 20%. Bisa di-adjust jadi paket yang lebih premium?",
    timestamp: "09:15",
  },
  {
    id: "comment-3",
    proposal_id: "prop-8",
    user_id: "user-4",
    user_name: "Dita Amelia",
    user_role: "ACS",
    content: "Mohon tambahan visual mockup untuk scene product placement yang disarankan.",
    timestamp: "14:45",
  },
  {
    id: "comment-4",
    proposal_id: "prop-9",
    user_id: "user-5",
    user_name: "Rizky Firmansyah",
    user_role: "Supervisor",
    content: "Overall proposal bagus, tapi client minta timeline yang lebih detail. Mohon direvisi.",
    timestamp: "16:20",
  },
]

export const statusLabels: Record<string, string> = {
  new: "Baru",
  in_review: "Review",
  in_progress: "Diproses",
  completed: "Selesai",
  new_brief: "New Brief",
  drafting: "Drafting",
  need_input: "Need Input",
  revised: "Revised",
  ready: "Ready",
}

export const clients: Client[] = [
  {
    id: "client-1",
    name: "Budi Santoso",
    brand_name: "Wardah",
    email: "budi@wardah.com",
    phone: "081234567890",
    company: "Parfame",
    industry: "Beauty & Personal Care",
    address: "Jakarta",
    notes: "Key account untuk Ramadan campaign",
    created_at: "2024-01-15",
    updated_at: "2024-05-20",
  },
  {
    id: "client-2",
    name: "Dewi Lestari",
    brand_name: "OPPO",
    email: "dewi@oppo.com",
    phone: "081234567891",
    company: "OPPO Indonesia",
    industry: "Technology",
    address: "Jakarta",
    notes: "Interested in youth-focused programs",
    created_at: "2024-02-01",
    updated_at: "2024-05-18",
  },
  {
    id: "client-3",
    name: "Ahmad Rizki",
    brand_name: "Indomie",
    email: "ahmad@indomie.com",
    phone: "081234567892",
    company: "Indofood",
    industry: "Food & Beverage",
    address: "Jakarta",
    notes: "Family-oriented brand, interested in reality shows",
    created_at: "2024-02-15",
    updated_at: "2024-05-17",
  },
]

export const events: Event[] = [
  {
    id: "event-1",
    title: "Deadline Proposal Wardah",
    description: "Proposal sinetron Ramadan harus selesai",
    event_date: "2025-05-27",
    event_time: "17:00",
    event_type: "deadline",
    reminder: true,
    reminder_days_before: 3,
    created_at: "2024-05-01",
    updated_at: "2024-05-01",
  },
  {
    id: "event-2",
    title: "Meeting dengan Client OPPO",
    description: "Review proposal Reno Series",
    event_date: "2025-05-28",
    event_time: "14:00",
    event_type: "meeting",
    reminder: true,
    reminder_days_before: 1,
    created_at: "2024-05-10",
    updated_at: "2024-05-10",
  },
  {
    id: "event-3",
    title: "Presentasi Indomie",
    description: "Family Moment campaign pitch",
    event_date: "2025-06-01",
    event_time: "10:00",
    event_type: "presentation",
    reminder: true,
    reminder_days_before: 2,
    created_at: "2024-05-15",
    updated_at: "2024-05-15",
  },
]

// Proposal Sections for Proposal Builder
export const proposalSections: Array<{ id: string; title: string; status: "completed" | "drafting" | "not_started" | "pending"; icon: string }> = [
  { id: "executive_summary", title: "Executive Summary", status: "drafting", icon: "file-text" },
  { id: "brand_overview", title: "Brand Overview", status: "completed", icon: "building" },
  { id: "audience_insight", title: "Audience Insight", status: "completed", icon: "users" },
  { id: "program_overview", title: "Program Overview", status: "not_started", icon: "tv" },
  { id: "integration_concept", title: "Integration Concept", status: "not_started", icon: "zap" },
  { id: "investment", title: "Investment Details", status: "not_started", icon: "dollar-sign" },
  { id: "timeline", title: "Timeline & Milestones", status: "not_started", icon: "calendar" },
  { id: "closing", title: "Closing", status: "not_started", icon: "check-circle" },
]

// Brand Explorer Data
export const brandExplorerData = {
  brand: {
    name: "Wardah",
    logo: "/wardah-logo.svg",
    industry: "Beauty & Personal Care",
    targetAudience: "Perempuan, 20-35 tahun",
    persona: "Modern Muslimah, Confident, Family Oriented",
    brandValue: "Halal, Natural, Inspiring, Trusted",
    competitors: ["Somethinc", "Emina", "Skintific", "Make Over"],
  },
  objective: "Meningkatkan brand awareness dan consideration selama Ramadan",
  program: "Sinetron Ramadan",
  budgetRange: "Rp 1.000.000.000 - 1.500.000.000",
  createdAt: "2025-05-21",
  insights: [
    {
      title: "Momen Ramadan sebagai opportunity",
      description: "Ramadan adalah momen yang tepat untuk memperkuat kedekatan brand dengan nilai spiritual, keluarga, dan kebaikan."
    },
    {
      title: "Perempuan ingin tampil terbaik saat Ramadan",
      description: "Target audience ingin tampil fresh & natural saat ibadah dan momen spesial bersama keluarga."
    },
    {
      title: "Media TV masih sangat relevan",
      description: "TV (terutama sinetron Ramadan) memiliki jangkauan luas di prime time saat keluarga berkumpul."
    },
  ],
  programFits: [
    { program: "Sinetron Ramadan", matchLevel: "best", description: "Sangat cocok untuk momen Ramadan dengan cerita keluarga" },
    { program: "Reality Show", matchLevel: "good", description: "Cocok untuk brand dengan tema keluarga" },
    { program: "Variety Show", matchLevel: "potential", description: "Potensi曝光 tinggi tapi perlu integrasi yang tepat" },
  ],
  integrationIdeas: [
    {
      type: "Segment Integration",
      idea: "Brand mention + product placement di scene memasak keluarga"
    },
    {
      type: "Digital Extension",
      idea: "Social media challenge #RamadanCeritaBaru"
    },
  ],
  packageRecommendation: {
    name: "Premium Package",
    value: "Rp 1.500.000.000",
    deliverables: [
      "Segment Integration 30 detik",
      "Product Placement di 5 episode",
      "Social Media Bundle",
      "Digital Extension Campaign"
    ]
  },
}
