/**
 * PitchFlow PDF Generator
 * Creates branded, professional PDF presentations for proposals
 */

import jsPDF from 'jspdf'

// Brand colors
const COLORS = {
  primary: '#061A3A',      // Deep navy
  secondary: '#2563EB',   // Bright blue
  accent: '#7C3AED',      // Purple (AI)
  red: '#E50914',         // Red accent
  white: '#FFFFFF',
  lightGray: '#F7F9FC',
  darkGray: '#64748B',
  black: '#1E293B',
}

// Proposal data interface
export interface ProposalData {
  title: string
  brand_name: string
  program: string
  industry: string
  sponsorship_type: string
  pic_sales: string
  deadline: string
  status: string
  result?: string
  year: number
  created_at?: string
  content?: {
    executive_summary?: string
    audience_insight?: string
    integration_concept?: string
    investment_details?: string
    timeline?: string
    [key: string]: string | undefined
  }
}

// Generate branded PDF proposal
export async function generateProposalPDF(
  proposal: ProposalData,
  options: {
    includeContent?: boolean
    logoUrl?: string
    primaryColor?: string
  } = {}
): Promise<Blob> {
  const {
    includeContent = true,
    logoUrl,
    primaryColor = COLORS.primary
  } = options

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - (margin * 2)

  // ========== COVER PAGE ==========
  // Dark header bar
  doc.setFillColor(hexToRgb(primaryColor))
  doc.rect(0, 0, pageWidth, 80, 'F')

  // Company name
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text('PITCHFLOW', margin, 20)

  // Logo placeholder (if provided)
  if (logoUrl) {
    try {
      // Add logo from URL
      const logoData = await fetch(logoUrl).then(r => r.blob())
      const logoBase64 = await blobToBase64(logoData)
      doc.addImage(logoBase64, 'PNG', pageWidth - 50, 15, 30, 20)
    } catch (e) {
      // Skip logo if fetch fails
    }
  }

  // Proposal title
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text(proposal.title || 'SPONSORSHIP PROPOSAL', margin, 45)

  // Brand name
  doc.setFontSize(18)
  doc.setFont('helvetica', 'normal')
  doc.text(proposal.brand_name, margin, 58)

  // Program name
  doc.setFontSize(14)
  doc.setTextColor(200, 200, 200)
  doc.text(proposal.program, margin, 70)

  // Reset text color
  doc.setTextColor(0, 0, 0)

  // Footer on cover
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Tahun ${proposal.year || new Date().getFullYear()}`, margin, pageHeight - 30)
  doc.text(`Disusun oleh: ${proposal.pic_sales || 'PitchFlow Team'}`, margin, pageHeight - 24)
  doc.text(`Tanggal: ${formatDate(proposal.created_at || new Date().toISOString())}`, margin, pageHeight - 18)

  // ========== CONTENT PAGES ==========
  let yPos = 100

  // Executive Summary
  if (includeContent && proposal.content?.executive_summary) {
    yPos = addSection(doc, 'EXECUTIVE SUMMARY', proposal.content.executive_summary, margin, yPos, contentWidth, pageHeight)
  }

  // Brand & Program Info
  yPos = addSection(doc, 'BRAND & PROGRAM', `Brand: ${proposal.brand_name}\nProgram: ${proposal.program}\nIndustri: ${proposal.industry}\nTipe Sponsorship: ${proposal.sponsorship_type}`, margin, yPos, contentWidth, pageHeight)

  // Audience Insight
  if (includeContent && proposal.content?.audience_insight) {
    yPos = addSection(doc, 'AUDIENCE INSIGHT', proposal.content.audience_insight, margin, yPos, contentWidth, pageHeight)
  }

  // Integration Concept
  if (includeContent && proposal.content?.integration_concept) {
    yPos = addSection(doc, 'INTEGRATION CONCEPT', proposal.content.integration_concept, margin, yPos, contentWidth, pageHeight)
  }

  // Investment Details
  if (includeContent && proposal.content?.investment_details) {
    yPos = addSection(doc, 'INVESTMENT DETAILS', proposal.content.investment_details, margin, yPos, contentWidth, pageHeight)
  }

  // Timeline
  if (includeContent && proposal.content?.timeline) {
    yPos = addSection(doc, 'TIMELINE', proposal.content.timeline, margin, yPos, contentWidth, pageHeight)
  }

  // ========== FOOTER ON ALL PAGES ==========
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)

    // Footer line
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.5)
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15)

    // Footer text
    doc.setFontSize(8)
    doc.setTextColor(100, 100, 100)
    doc.text(`Halaman ${i} dari ${totalPages}`, margin, pageHeight - 10)
    doc.text('Generated by PitchFlow', pageWidth - margin - 40, pageHeight - 10)
    doc.text(formatDate(new Date().toISOString()), pageWidth - margin - 40, pageHeight - 6)
  }

  return doc.output('blob')
}

// Helper: Add a section to the PDF
function addSection(
  doc: jsPDF,
  title: string,
  content: string,
  margin: number,
  startY: number,
  contentWidth: number,
  pageHeight: number
): number {
  // Check if we need a new page
  if (startY > pageHeight - 50) {
    doc.addPage()
    return 30
  }

  let yPos = startY

  // Section title with accent bar
  doc.setFillColor(hexToRgb(COLORS.secondary))
  doc.rect(margin, yPos, 4, 12, 'F')

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text(title, margin + 8, yPos + 9)

  yPos += 18

  // Section content
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(50, 50, 50)

  const lines = doc.splitTextToSize(content, contentWidth - 5)

  // Check for page overflow
  for (const line of lines) {
    if (yPos > pageHeight - 25) {
      doc.addPage()
      yPos = 25
    }
    doc.text(line, margin + 5, yPos)
    yPos += 6
  }

  yPos += 10 // Add spacing after section
  return yPos
}

// Helper: Convert hex color to RGB array
function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [0, 0, 0]
}

// Helper: Format date to Indonesian locale
function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  return date.toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  })
}

// Helper: Convert blob to base64
function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => resolve(reader.result as string)
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

// Download PDF
export function downloadPDF(blob: Blob, filename: string = 'proposal.pdf') {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
