/**
 * PDF Export utilities for PitchFlow
 * Uses browser print functionality for PDF generation
 */

/**
 * Generate PDF from HTML element
 */
export async function generatePDFFromHTML(elementId: string, filename: string = 'pitchflow-document.pdf') {
  const element = document.getElementById(elementId)
  if (!element) {
    console.error('Element not found:', elementId)
    return false
  }

  try {
    // Use window.print() for PDF generation
    // The user can use "Print to PDF" option in their browser
    window.print()
    return true
  } catch (error) {
    console.error('PDF generation failed:', error)
    return false
  }
}

/**
 * Download data as JSON file
 */
export function downloadAsJSON(data: unknown, filename: string = 'pitchflow-data.json') {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Download data as CSV file
 */
export function downloadAsCSV(data: Record<string, unknown>[], filename: string = 'pitchflow-data.csv') {
  if (data.length === 0) return

  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(','),
    ...data.map(row =>
      headers.map(header => {
        const value = row[header]
        // Escape quotes and wrap in quotes if contains comma
        if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
          return `"${value.replace(/"/g, '""')}"`
        }
        return value ?? ''
      }).join(',')
    )
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch (error) {
    console.error('Copy to clipboard failed:', error)
    return false
  }
}

/**
 * Print document
 */
export function printDocument() {
  window.print()
}

/**
 * Export proposal as formatted text
 */
export function exportProposalAsText(proposal: {
  title: string
  brand_name: string
  program: string
  industry: string
  sponsorship_type: string
  status: string
  pic_sales: string
  deadline: string
}): string {
  return `
═══════════════════════════════════════════════════════════════
                    PITCHFLOW PROPOSAL
═══════════════════════════════════════════════════════════════

TITLE: ${proposal.title}
BRAND: ${proposal.brand_name}
PROGRAM: ${proposal.program}
INDUSTRY: ${proposal.industry}
SPONSORSHIP TYPE: ${proposal.sponsorship_type}
STATUS: ${proposal.status}
PIC SALES: ${proposal.pic_sales}
DEADLINE: ${proposal.deadline}

═══════════════════════════════════════════════════════════════
Generated by PitchFlow - ${new Date().toLocaleString('id-ID')}
═══════════════════════════════════════════════════════════════
  `.trim()
}

/**
 * Download proposal as text file
 */
export function downloadProposalAsText(proposal: Record<string, unknown>) {
  const content = exportProposalAsText(proposal as Parameters<typeof exportProposalAsText>[0])
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `proposal-${proposal.title || 'document'}-${Date.now()}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
